export class CommericalLawData {
    CommercialRegistrationNo?:number;
    ActOfIncorporation?:number;
    ActOfIncorporationId?:number;
    CompanyType?:string;
    CompositionBy?:string;
    CompositionDate?:Date;
    CompositionGeha?:string;
    CompositionNumber?:number;
    EsmTojary?:string;
    GovernorateID?:number;
    NickName?:string;
    OrganizationDetailedType?:number;
    OrganizationStatus?:string;
    RegisterCommercialID:number;
    Sefa?:number;
    SemaTojarya?:string;
    ShahrAqaryID?:number;
    TalebAltarkhees?:string;
    TawkeelKind?:string;
    TawkeelNumber?:number;
}